### ISSUE TITLE
Error: While trying to apply extra data: apply_extra script failed, exit status 512

### ISSUE THREAD

**Issue by 2GetApp** [flathub/com.jetbrains.PyCharm-Professional#278]
Running `flatpak update` to update pycharm gave following error:
"Error: While trying to apply extra data: apply_extra script failed, exit status 512"

My environment is Flatpak 1.15.8 on Silverblue 40.
I am not sure whether it's flatpak's problem or pycharm's, but I can install other proprietary apps (e.g. com.axosoft.GitKraken).

**Comment by ghisvail** [comment]
Same here on Mint 22 (Flatpak version 1.14.6)

**Comment by ghisvail** [comment]
It fails at the apply_extra stage, i.e. the following commands:

```yaml
      - type: script
        dest-filename: apply_extra
        commands:
          - set -ex
          - tar xf pycharm-professional.tar.gz --strip-components 1
          - rm -f pycharm-professional.tar.gz
          - cat /app/idea.properties | tee -a /app/extra/bin/idea.properties
          - python3 /app/extra/plugins/python/helpers/pydev/setup_cython.py build_ext
            --inplace
```

are failing with the new update.
