### ISSUE TITLE
any ideas on how to get python 3.10 ?

### ISSUE THREAD

**Issue by freeseacher** [flathub/com.jetbrains.PyCharm-Professional#49]
I know that i can use conda for this but i want to use poetry for package management. 
may be there are some obvious way in how to get python 3.10 without it in flatpack environment ?

**Comment by freeseacher** [comment]
after https://github.com/flathub/com.jetbrains.PyCharm-Professional/pull/50
we can just add something like 

```
id: com.jetbrains.PyCharm.Extensions.Python310
branch: "21.08"
runtime: com.jetbrains.PyCharm-Professional
runtime-version: test
sdk: org.freedesktop.Sdk//21.08
build-extension: true
appstream-compose: false
build-options: 
  prefix: /app/extensions/Python310
modules:
  - name: python3.10
    sources:
      - type: archive
        url: https://www.python.org/ftp/python/3.10.2/Python-3.10.2.tgz
        md5: 67c92270be6701f4a6fed57c4530139b
```

and actually i've done it on my laptop. the real question is how to add this extension to flathub. because obviously i'm not on the list https://github.com/flathub/flathub/wiki/App-Submission#theres-an-app-that-id-like-to-see-on-flathub-but-im-not-the-developer
